# Generated by Django 3.2.20 on 2023-08-25 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_name', models.CharField(max_length=25)),
                ('number_of_items', models.IntegerField(default=1)),
                ('personal_message', models.TextField(blank=True)),
                ('booking_date', models.DateField()),
                ('home_delivery', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=100)),
                ('delivery_time', models.IntegerField(choices=[(1, 'morning'), (2, 'afternoon'), (3, 'evening')], default=1)),
                ('completed', models.BooleanField(default=False)),
                ('booked_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_item', to='menu.menuitem')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['booking_date', 'delivery_time'],
            },
        ),
    ]
