# Generated by Django 3.2.20 on 2023-11-28 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_name', models.CharField(max_length=25)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('number_of_items', models.IntegerField(default=1)),
                ('personal_message', models.CharField(blank=True, max_length=100)),
                ('booking_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('booked_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_item', to='menu.menuitem')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['booking_date'],
            },
        ),
    ]
