# Generated by Django 3.2.20 on 2023-08-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='personal_message',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
