# Generated by Django 3.2.20 on 2023-08-30 21:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_personal_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='personal_message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
